quad:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: sonar_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
